let codePosts = [
    {
        id: "a5",
        title: "Special Offer",
        year: "2023",
        desc: "I worked as a Frontend Software Engineer Intern at a creative tech company, working on sites like UNIF, dis, Major Food Group, Laura Lombardi, Roses, and internal boilerplates.",
        images: ["/code/special-offer.png"],
        genre: ["Frontend"],
        tags: ["Nuxt.js, HTML/CSS, Vue.js, git, Vercel, Shopify Liquid, Sanity.io"],
        links: [["https://www.specialoffer.inc/", "Special Offer Website"], ["https://unifclothing.com", "UNIF"], ["https://www.lauralombardi.com/","Laura Lombardi"], ["https://dis.art/", "dis"], ["https://www.majorfood.com/","MFG"], ["https://rosesmetals.com/","Roses"]],
        slidelayout: "trad",
        cardlayout: "single-7"
    },
    {
        id: "a3",
        title: "odyXxey",
        year: "2022-",
        desc: "I am the Coding Lead at odyXxey, working closely with a designer and founder to develop the new website with a radio station, e-commerce store, event calendar, and archive.",
        images: ["/code/odyxxey-3.png","/code/odyxxey-2.png", "/code/odyxxey-1.png", "/code/odyxxey-4.png"],
        genre: ["Full Stack"],
        tags: ["Next.js, HTML/CSS, React, git, Vercel, Shopify Storefront API, Soundcloud API, Airtime Pro API, Sanity.io"],
        links: [["https://odyxxey.com", "Website"]],
        slidelayout: "trad-code",
        cardlayout: "single"
    },
    {
        id: "a4",
        title: "Annalect",
        year: "2022-2023",
        desc: "I was a Frontend Software Engineer Apprentice working with Senior Frontend Software Engineers and the Director of Engineering to develop a campaign analysis web application for Meta through agile methodology.",
        images: ["/code/annalect.png"],
        genre: ["Frontend"],
        tags: ["HTML/CSS, Lit, Bitbucket, Jira, API, JavaScript"],
        links: [["https://www.annalect.com/", "Annalect Website"]],
        slidelayout: "trad",
        cardlayout: "single-7"
    },
    {
        id: "a1",
        title: "P12",
        year: "2022",
        desc: "I developed frontend components for P12's landing page, learning and improving my problem solving and technical skills over existing code in a bilingual team setting.",
        images: null,
        genre: ["Frontend"],
        tags: ["Internship, React, TailwindCSS, git"],
        links: [["https://p12.network", "Website"]],
        slidelayout: "trad",
        cardlayout: "single-7"
    },
    {
        id: "a2",
        title: "Pigeon Sale",
        year: "2021",
        desc: "I designed, built, and developed frontend components for an e-commerce secondhand trading system, practicing software engineering methodologies with a team over a span of 2 months.",
        images: ["/code/pigeonsale.jpg", "/code/pigeonsale-2.jpg",  "/code/pigeonsale-3.jpg", "/code/pigeonsale-4.jpg", "/code/pigeonsale-5.jpg", "/code/pigeonsale-6.jpg","/code/pigeonsale-7.jpg","/code/pigeonsale-8.jpg","/code/pigeonsale-9.jpg","/code/pigeonsale-10.jpg"],
        genre: ["Frontend"],
        tags: ["Group Project, Software Engineering, React, MUI, SaSS, Flask, Fetch API, Redis, git"],
        links: [["https://github.com/Harrilee/PigeonSale/tree/main/frontend", "GitHub"]],
        slidelayout: "trad-code",
        cardlayout: "single"
    },
    {
        id: "a3",
        title: "AuxNow",
        year: "2020",
        desc: "I built a full stack application using Spotify API to build on my knowledge with React and API workflow.",
        images: ["/code/auxnow.jpg", "/code/auxnow-2.jpg", "/code/auxnow-3.jpg",
        "/code/auxnow-4.jpg", "/code/auxnow-5.jpg", "/code/auxnow-6.jpg","/code/auxnow-7.jpg","/code/auxnow-8.jpg"],
        genre: ["Full Stack"],
        tags: ["Self-taught, React, Node.js, Spotify API"],
        links: [["https://github.com/robinpx/auxnow", "GitHub"]],
        slidelayout: "trad-code",
        cardlayout: "single"
    },
    {
        id: "a4",
        title: "dataverses",
        year: "2020",
        images: ["/code/dataverses.jpg"],
        desc: "I played with the API data of Cooper Hewitt's graphic design catologue to algorithmically create Gertrude Stein inspired poems and using extracted colors from their images.",
        genre: ["Flask"],
        tags: ["Flask, Python, BeautifulSoup, HTML/CSS, urllib, spaCy"],
        links: [["https://github.com/robinpx/dataverses", "GitHub"]],
        slidelayout: "trad-code",
        cardlayout: "single"
    },
    {
        id: "a5",
        title: "Tumblr Boombox",
        year: "2018",
        desc: "I built a client-side audio player that plays audio from a Tumblr user's account.",
        images: ["/code/boombox.jpg", "/code/boombox2.jpg"],
        genre: ["Frontend"],
        tags: ["Self-taught, HTML/CSS, JavaScript, jQuery, Tumblr API"],
        links: [["https://github.com/robinpx/boombox", "GitHub"], ["https://robinpx.github.io/boombox", "Website"]],
        slidelayout: "trad-code",
        cardlayout: "single"
    },
    // {
    //     id: "b1",
    //     title: "Complexity and Demonstration of Quantum Supremacy Algorithms",
    //     year: "2022",
    //     images: null,
    //     desc: "I researched and developed a program to prove quantum supremacy algorithms with Qiskit, IBM Q, and Python for my senior capstone.",
    //     genre: ["Research"],
    //     tags: ["Group Project, Python, Qiskit, IBM Q, Jupyter Notebook"],
    //     links: [["https://github.com/robinpx/quantum-algorithms", "GitHub"], ["/code/capstone.pdf", "Report"]],
    //     slidelayout: "trad",
    //     cardlayout: "single-7"
    // },
    // {
    //     id: "b2",
    //     title: "ALTAR-3000",
    //     year: "2021-2022",
    //     images: null,
    //     desc: "I developed the robotics and web scraping program for a media artist's AI Prophetic Robot Arm.",
    //     genre: ["Programming"],
    //     tags: ["Artist Collaboration, Python, C++, ROS, Selenium, OOP"],
    //     links: [["https://github.com/robinpx/chronus", "GitHub"], ["https://vjnks.com/works/altar-3000", "Documentation"]],
    //     slidelayout: "trad",
    //     cardlayout: "single"
    // },
];

export default(codePosts);
